version: 2.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
init:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Server:
    secure: UzHGGTiu63CYQPT9rPKhJA==
  Database:
    secure: DqXxLd3D/+1o2EtQvqhbgA==
  User:
    secure: UzHGGTiu63CYQPT9rPKhJA==
  Password:
    secure: aii6TuA5V1pzlqRiUOXyTQ==
  APPVEYOR_RDP_PASSWORD:
    secure: aii6TuA5V1pzlqRiUOXyTQ==
install:
- ps: Install-Product node 8
before_build:
- cmd: >-
    dotnet restore


    cd ./src/Etymology.Web

    npm install
build:
  parallel: true
  verbosity: detailed
test: off