version: 2.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Etymology:
    secure: EXqa8qHo22jd/nq17/myGbk077tkDDe22+jT/Jxl1SBNTkWct5r/PY1QgSporP57OD1X5saev6hfDQHy4ZjU9F4C/m8/Sf2IFzSNaeHE/fsAxpe8UmuvXFZ4Suzh8/54GlWd/8wV9PPTaIVyf0bLdLjVexbqw2+Nttv6ycu/CBzsUz/SLSR4BdmLzZtmk/IwvnUgkyLWaS91S41DnwRunZ1a2us5WFWBOB164C3QbWbDQNopjcGjQnFe6zc9eVwwx62FzGjqAegtudV7ly3vY6l4ol0N+KQVedFles3w7w3lg6+62AXAAbno7zif0sqTdPY7I9exVEoNd1uxndUUKA==
  APPVEYOR_RDP_PASSWORD:
    secure: aii6TuA5V1pzlqRiUOXyTQ==
  ASPNETCORE_ENVIRONMENT: Staging
install:
- ps: Install-Product node Current
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: normal
artifacts:
- path: ./Publish/Release
  name: PublishRelease