title: Chinese Etymology 字源 hanziyuan.net
author: Dixin
description: > # this means to ignore newlines until "baseurl:"
  Chinese Etymology 字源 hanziyuan.net
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
permalink: /:title

# social links
github_username:  Dixin # DO NOT include the @ character, or else the build will fail!
